<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.massivecraft</groupId>
        <artifactId>Factions</artifactId>
        <version>1.6.9.5-4.2.5</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>factions-shared</artifactId>
    <packaging>jar</packaging>

    <name>SaberFactions Shared</name>

    <build>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src/main/resources/</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M7</version>
            </plugin>
        </plugins>
    </build>

    <dependencies>

        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>${spigot.api.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.9.12</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.github.Driftay</groupId>
            <artifactId>WorldGuard-Bridge</artifactId>
            <version>6c80848837</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>de.tr7zw</groupId>
            <artifactId>item-nbt-api</artifactId>
            <version>2.15.5</version>
        </dependency>
        <dependency>
            <groupId>me.lucko</groupId>
            <artifactId>commodore</artifactId>
            <version>2.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.mojang</groupId>
            <artifactId>brigadier</artifactId>
            <version>1.0.14</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.github.cryptomorin</groupId>
            <artifactId>XSeries</artifactId>
            <version>13.6.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.14.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>net.milkbowl.vault</groupId>
            <artifactId>VaultAPI</artifactId>
            <version>1.7</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <artifactId>bukkit</artifactId>
                    <groupId>org.bukkit</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>be.maximvdw</groupId>
            <artifactId>MVdWPlaceholderAPI</artifactId>
            <version>3.1.1-SNAPSHOT</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.spigotmc</groupId>
                    <artifactId>spigot</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.sk89q.worldedit</groupId>
            <artifactId>worldedit-bukkit</artifactId>
            <version>6.1.1-SNAPSHOT</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <artifactId>bukkit</artifactId>
                    <groupId>org.bukkit</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jsr305</artifactId>
                    <groupId>com.google.code.findbugs</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>bukkit-classloader-check</artifactId>
                    <groupId>org.sk89q.bukkit</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>dummypermscompat</artifactId>
                    <groupId>com.sk89q</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jchronic</artifactId>
                    <groupId>com.sk89q</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>js</artifactId>
                    <groupId>rhino</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>truezip</artifactId>
                    <groupId>de.schlichtherle</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jlibnoise</artifactId>
                    <groupId>com.sk89q.lib</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>paranamer</artifactId>
                    <groupId>com.thoughtworks.paranamer</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>guava</artifactId>
                    <groupId>com.google.guava</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>gson</artifactId>
                    <groupId>com.google.code.gson</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>snakeyaml</artifactId>
                    <groupId>org.yaml</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>dev.rosewood</groupId>
            <artifactId>rosestacker</artifactId>
            <version>1.2.6</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.bgsoftware</groupId>
            <artifactId>WildStackerAPI</artifactId>
            <version>2022.6</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.ess3</groupId>
            <artifactId>EssentialsX</artifactId>
            <version>2.18.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.ess3</groupId>
            <artifactId>EssentialsXChat</artifactId>
            <version>2.0.1</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <artifactId>bukkit</artifactId>
                    <groupId>org.bukkit</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>lombok</artifactId>
                    <groupId>org.projectlombok</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>Essentials</artifactId>
                    <groupId>net.ess3</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-api</artifactId>
            <version>4.24.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-text-serializer-legacy</artifactId>
            <version>4.24.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-text-serializer-gson</artifactId>
            <version>4.24.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>net.kyori</groupId>
            <artifactId>adventure-platform-bukkit</artifactId>
            <version>4.4.1</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.dynmap</groupId>
            <artifactId>dynmap</artifactId>
            <version>2.0</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <artifactId>bukkit</artifactId>
                    <groupId>org.bukkit</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>Permissions</artifactId>
                    <groupId>com.nijikokun.bukkit</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>bPermissions</artifactId>
                    <groupId>de.bananaco</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>EssentialsGroupManager</artifactId>
                    <groupId>org.anjocaido</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>spoutpluginapi</artifactId>
                    <groupId>org.getspout</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>PermissionsBukkit</artifactId>
                    <groupId>com.platymuus.bukkit.permissions</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>PermissionsEx</artifactId>
                    <groupId>ru.tehkode</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>32.0.1-android</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <artifactId>jsr305</artifactId>
                    <groupId>com.google.code.findbugs</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.11.6</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>me.clip.placeholderapi.libs.kyori</groupId>
                    <artifactId>adventure-platform-bukkit</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>me.clip.placeholderapi.libs.kyori</groupId>
                    <artifactId>adventure-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>me.clip.placeholderapi.libs.kyori</groupId>
                    <artifactId>adventure-text-serializer-gson</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>me.clip.placeholderapi.libs.kyori</groupId>
                    <artifactId>adventure-text-serializer-legacy</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.mojang</groupId>
            <artifactId>authlib</artifactId>
            <version>1.5.21</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-bukkit</artifactId>
            <version>3.0.1</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
