<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.massivecraft</groupId>
        <artifactId>Factions</artifactId>
        <version>1.6.9.5-4.2.5</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>factions-legacy</artifactId>
    <packaging>jar</packaging>

    <name>SaberFactions Legacy</name>

    <dependencies>
        <dependency>
            <groupId>com.massivecraft</groupId>
            <artifactId>factions-shared</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>${legacy.spigot.api.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
